### PR TITLE
Add multiple stock retrieval and percentage change

### PR DESCRIPTION
**Pull request by PandaStacker**
Duplicated code to allow gathering percentage change and gathering multiple percentage changes at once. Also threw in a script as an example of how to use all of this.

### CODE REVIEW

**Comment by PandaStacker** [comment]
I didn't think you'd come out with V2 so fast! There's conflicts but you can just move the new code.

**Comment by PatzEdi** [comment]
Hello! Wow, I did not expect anyone to create a Pull Request! This is super cool, and is my first time handling a pull request, so sorry if it takes me a while to inspect it and possibly merge it. Thank you so much for the time and support taken toward Stockstir! I will take a look at the code and check it out.

Edit: After taking a look at the additional features/code, ideas such as the multi stock data gathering function and the get percentage are really good! Thank you for also providing a script to showcase how these new implementations would be used. However, there are conflicts as you pointed out as well. Would it be fine if I were to implement such ideas in the code, without merging the pull request itself? I would, of course, create a new CONTRIBUTORS.md file, as well as create a new Contributors list right under the logo in the README file, and put your username there for credit, as well as put your username in the code itself where the new functions are going to be located, and link the pull request. This is my first time having anyone contribute to one of my projects, so if there is a better way to manually add contributors without having to merge the pull request that you know of, I would be glad to know. Thanks again for the support and the time taken to improve Stockstir!

**Comment by PandaStacker** [comment]
Oh haha, sorry I should have made it more straightforward then, it’s just your code copied and modified for new values. I didn’t really do anything new. It’s a fun project, I’d been thinking of doing the same thing then I saw your post on Reddit.Envoyé de mon iPhoneLe 31 déc. 2023 à 17:36, Edward Ferrari ***@***.***> a écrit :﻿
Hello! Wow, I did not expect anyone to create a Pull Request! This is super cool, and is my first time handling a pull request, so sorry if it takes me a while to inspect it and possibly merge it. Thank you so much for the time and support taken toward Stockstir! I will take a look at the code and check it out.

**Comment by PatzEdi** [comment]
> Oh haha, sorry I should have made it more straightforward then, it’s just your code copied and modified for new values. I didn’t really do anything new. It’s a fun project, I’d been thinking of doing the same thing then I saw your post on Reddit.Envoyé de mon iPhoneLe 31 déc. 2023 à 17:36, Edward Ferrari ***@***.***> a écrit :﻿ Hello! Wow, I did not expect anyone to create a Pull Request! This is super cool, and is my first time handling a pull request, so sorry if it takes me a while to inspect it and possibly merge it. Thank you so much for the time and support taken toward Stockstir! I will take a look at the code and check it out. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Thank you again! Will definitely integrate the code within Stockstir in the next release, which also fixes other things such as Python formatting guidelines. These ideas will for sure enhance usability. Thanks!

**Comment by PatzEdi** [comment]
Thank you PandaStacker! Your idea of the multi ticker data gathering has been implemented into Stockstir in the latest release. You are now included in the credits of the Documentation, as well as the latest Reddit post about Stockstir. I hope you enjoy the new update!

**Pull request closed without merging**
